#!/usr/bin/env python3
"""Regenerate packaging/flatpak/python-deps.yml with wheels pinned by hash.

Flathub builds offline, so every wheel is listed with its URL and sha256.
Run after changing a dependency, or when the GNOME runtime's Python version moves:

    python tools/gen_flatpak_deps.py --python 313
"""
import argparse,hashlib,json,shutil,subprocess,sys,urllib.request
from pathlib import Path

ROOT=Path(__file__).resolve().parent.parent
PKGS=['simplemma','piper-tts']          # their dependency trees come along
OUT=ROOT/'packaging/flatpak/python-deps.yml'

def main(py,platform):
    tmp=ROOT/'.wheels';shutil.rmtree(tmp,ignore_errors=True);tmp.mkdir()
    subprocess.run([sys.executable,'-m','pip','download','--only-binary=:all:','--python-version',py,
                    '--implementation','cp','--platform',platform,'--dest',str(tmp),*PKGS],check=True)
    lines=['# Generated by tools/gen_flatpak_deps.py - do not edit by hand.',
           f'# Wheels for the GNOME runtime (Python 3.{py[1:]}, x86_64), pinned by hash so the build is offline.',
           'name: python-deps','buildsystem: simple','build-commands:',
           '  - pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}"',
           '    --prefix=${FLATPAK_DEST} --no-build-isolation']
    wheels=sorted(tmp.glob('*.whl'))
    lines.append('    '+' '.join(sorted({w.name.split('-')[0].replace('_','-') for w in wheels})))
    lines.append('sources:')
    for w in wheels:
        pkg,ver=w.name.split('-')[0].replace('_','-'),w.name.split('-')[1]
        meta=json.load(urllib.request.urlopen(f'https://pypi.org/pypi/{pkg}/{ver}/json'))
        entry=next(u for u in meta['urls'] if u['filename']==w.name)
        sha=hashlib.sha256(w.read_bytes()).hexdigest()
        if sha!=entry['digests']['sha256']:sys.exit(f'hash mismatch for {w.name}')
        lines+=['  - type: file',f'    url: {entry["url"]}',f'    sha256: {sha}']
    OUT.write_text('\n'.join(lines)+'\n')
    shutil.rmtree(tmp)
    print(f'{OUT}: {len(wheels)} wheels')

if __name__=='__main__':
    a=argparse.ArgumentParser();a.add_argument('--python',default='313')
    a.add_argument('--platform',default='manylinux_2_28_x86_64');a=a.parse_args()
    main(a.python,a.platform)
